#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "owncloud"
name = "ownCloud"
description.en = "Online storage, file sharing platform"
description.fr = "Stockage en ligne, plateforme de partage de fichiers"

version = "8.0.5~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://owncloud.com"
demo = "https://ocis.owncloud.com"
admindoc = "https://doc.owncloud.com/ocis/next/"
code = "https://github.com/owncloud/ocis"
cpe = "cpe:2.3:a:owncloud:owncloud"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "100M"
ram.build = "800M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/owncloud/ocis/releases/download/v8.0.5/ocis-8.0.5-linux-amd64"
    amd64.sha256 = "2beebb3a8fd721f091688f298974d53d11fe2f04be0f374739dd091cf80bce61"
    arm64.url = "https://github.com/owncloud/ocis/releases/download/v8.0.5/ocis-8.0.5-linux-arm64"
    arm64.sha256 = "c1bb05016e0a943684c90cc6a9ab482008082af2e91bd7c959a2a34a342903db"
    armhf.url = "https://github.com/owncloud/ocis/releases/download/v8.0.5/ocis-8.0.5-linux-arm"
    armhf.sha256 = "038ddcf67af918374af24ec4c0ad8c2afe05efb472d129659adfdc0c58c6d3df"
    i386.url = "https://github.com/owncloud/ocis/releases/download/v8.0.5/ocis-8.0.5-linux-386"
    i386.sha256 = "47374f985a53475ca5533120176d1131e048d682c277119a2742bc37334ffa0f"
    in_subdir = false
    rename = "ocis"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^ocis-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^ocis-.*-linux-arm64$"
    autoupdate.asset.armhf = "^ocis-.*-linux-arm$"
    autoupdate.asset.i386 = "^ocis-.*-linux-386$"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["config"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/ocs"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors"]

    [resources.ports]
