#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "owncloud"
name = "ownCloud"
description.en = "Online storage, file sharing platform"
description.fr = "Stockage en ligne, plateforme de partage de fichiers"

version = "8.1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://owncloud.com"
demo = "https://ocis.owncloud.com"
admindoc = "https://doc.owncloud.com/ocis/next/"
code = "https://github.com/owncloud/ocis"
cpe = "cpe:2.3:a:owncloud:owncloud"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "100M"
ram.build = "800M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/owncloud/ocis/releases/download/v8.1.0/ocis-8.1.0-linux-amd64"
    amd64.sha256 = "8e119331991e80a658400884c17e4b5fd8ab52e073ae133386500a5d5503eb25"
    arm64.url = "https://github.com/owncloud/ocis/releases/download/v8.1.0/ocis-8.1.0-linux-arm64"
    arm64.sha256 = "ef094e066ff1282a6145715b56196c429365d37fe83c7a99eaa91bcfa54203a5"
    armhf.url = "https://github.com/owncloud/ocis/releases/download/v8.1.0/ocis-8.1.0-linux-arm"
    armhf.sha256 = "761bebee68e031b32a569021a80c5484db46058bfeec97c9200dc5eabd54454b"
    i386.url = "https://github.com/owncloud/ocis/releases/download/v8.1.0/ocis-8.1.0-linux-386"
    i386.sha256 = "b0fbfb1f7ccc363dab70fee13a791a92cb1d3ec87256ef759b18e16e36b5a10d"
    in_subdir = false
    rename = "ocis"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^ocis-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^ocis-.*-linux-arm64$"
    autoupdate.asset.armhf = "^ocis-.*-linux-arm$"
    autoupdate.asset.i386 = "^ocis-.*-linux-386$"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["config"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/ocs"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors"]

    [resources.ports]
