#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

timezone=$(cat /etc/timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod +x $install_dir/ocis

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="File sharing platform" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$data_dir/config/ocis.env"

chmod 400 "$data_dir/config/ocis.env"
chown $app:$app "$data_dir/config/ocis.env"

#=================================================
# INSTALL OWNCLOUD
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	./ocis init --insecure=true --force-overwrite=true --admin-password=$password --config-path=$data_dir/config/
popd

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chown $app:$app "$data_dir/config/ocis.yaml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl  --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
